import './globals.css'
import { Inter } from 'next/font/google'
import Menu from './Menu'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
    <body className={inter.className}>
    <header className="App-header">
    <Image width={300} height={300} alt='Kanté construction Logo' src="/KanteConstructionLogo.png"/>
    <Menu/>
    </header>
    {children}
    <footer>
    
    </footer>
    </body>
    </html>
    )
  }
